image: maven:3.5.0-jdk-8

buildAndTest:
  script:
    - backend/mvn verify --batch-mode
  artifacts:
    paths:
      - backend/target/*
    expire_in: 5min

    
variables:
  GIT_SSL_NO_VERIFY: "1"


    
variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS:   "4333796"
