image: maven:3.5.0-jdk-8

buildAndTest:
  script:
    - backend/cookify/mvn verify --batch-mode
  artifacts:
    paths:
      - backend/cookify/target/*
    expire_in: 5min

    
variables:
  GIT_SSL_NO_VERIFY: "1"

